//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHOHOH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res_ch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_ch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HHOHOH.Resources.Res.ch", typeof(Res_ch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction d&apos;un bogue face à face.
        /// </summary>
        internal static string amap_Text {
            get {
                return ResourceManager.GetString("amap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le dossier de sauvegarde.
        /// </summary>
        internal static string backup_Menu {
            get {
                return ResourceManager.GetString("backup_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de sauvegarde.
        /// </summary>
        internal static string backup_Status {
            get {
                return ResourceManager.GetString("backup_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec de la sauvegarde.
        /// </summary>
        internal static string backup_Status_Failed {
            get {
                return ResourceManager.GetString("backup_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;il vous plaît Ouvrez une ROM ou autrement snek vous mangera.
        /// </summary>
        internal static string blankpage_Text {
            get {
                return ResourceManager.GetString("blankpage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Système BW Repel.
        /// </summary>
        internal static string bw_Text {
            get {
                return ResourceManager.GetString("bw_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce hack est pour FireRed v1 seulement, et utilise l&apos;espace libre pour environ 0x80 octets. Si vous avez utilisé cet espace, il l&apos;écrasera et effacera vos données, ce qui pourrait entraîner une corruption ou un mauvais script. Cliquez sur Oui si vous comprenez les risques..
        /// </summary>
        internal static string bw_Warning {
            get {
                return ResourceManager.GetString("bw_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode de débogage.
        /// </summary>
        internal static string debugging_Menu {
            get {
                return ResourceManager.GetString("debugging_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dex Vu dans le menu.
        /// </summary>
        internal static string dexSeen_Text {
            get {
                return ResourceManager.GetString("dexSeen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau 1 Bébés.
        /// </summary>
        internal static string egg_Text {
            get {
                return ResourceManager.GetString("egg_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string en_Menu {
            get {
                return ResourceManager.GetString("en_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Évolution sans Dex national.
        /// </summary>
        internal static string evo_Text {
            get {
                return ResourceManager.GetString("evo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer Flashbacks.
        /// </summary>
        internal static string flashback_Text {
            get {
                return ResourceManager.GetString("flashback_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string fr_Menu {
            get {
                return ResourceManager.GetString("fr_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez un emplacement d&apos;espace libre de 0x80 octets de longueur. Cochez &apos;0x&apos;..
        /// </summary>
        internal static string freespace_Warning {
            get {
                return ResourceManager.GetString("freespace_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a location of free space 0x650 bytes in length.Leave out &apos;0x&apos;..
        /// </summary>
        internal static string freespace_Warning2 {
            get {
                return ResourceManager.GetString("freespace_Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixer l&apos;herbe haute.
        /// </summary>
        internal static string grass_Text {
            get {
                return ResourceManager.GetString("grass_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression des HM.
        /// </summary>
        internal static string hm_Text {
            get {
                return ResourceManager.GetString("hm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langues.
        /// </summary>
        internal static string languages_Menu {
            get {
                return ResourceManager.GetString("languages_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Legendary IV RNG.
        /// </summary>
        internal static string legend_Text {
            get {
                return ResourceManager.GetString("legend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obéissance Mew forcée.
        /// </summary>
        internal static string mew_Text {
            get {
                return ResourceManager.GetString("mew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        internal static string more_Menu {
            get {
                return ResourceManager.GetString("more_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avis.
        /// </summary>
        internal static string notice_Warning {
            get {
                return ResourceManager.GetString("notice_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvert.
        /// </summary>
        internal static string open_Menu {
            get {
                return ResourceManager.GetString("open_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactiver OW Poison.
        /// </summary>
        internal static string poison_Text {
            get {
                return ResourceManager.GetString("poison_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokedex Fix.
        /// </summary>
        internal static string pokedex_Text {
            get {
                return ResourceManager.GetString("pokedex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaussures de course sans drapeau.
        /// </summary>
        internal static string runFlag_Text {
            get {
                return ResourceManager.GetString("runFlag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courir à l&apos;intérieur.
        /// </summary>
        internal static string running_Text {
            get {
                return ResourceManager.GetString("running_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string sp_Menu {
            get {
                return ResourceManager.GetString("sp_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colored Stats.
        /// </summary>
        internal static string st_Text {
            get {
                return ResourceManager.GetString("st_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This hack is for FireRed v1 only, and uses the freespace for around 0x650 bytes. If you have used this space it will overwrite it and delete your data which could result in corruption or a bad script. Click yes if you understand the risks..
        /// </summary>
        internal static string st_Warning {
            get {
                return ResourceManager.GetString("st_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajoutée!.
        /// </summary>
        internal static string Status_Add {
            get {
                return ResourceManager.GetString("Status_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlevé!.
        /// </summary>
        internal static string Status_Remove {
            get {
                return ResourceManager.GetString("Status_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string warning_Warning {
            get {
                return ResourceManager.GetString("warning_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue!.
        /// </summary>
        internal static string welcome_Status {
            get {
                return ResourceManager.GetString("welcome_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERREUR.
        /// </summary>
        internal static string write_ERROR {
            get {
                return ResourceManager.GetString("write_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM manquant.
        /// </summary>
        internal static string write_NoROM {
            get {
                return ResourceManager.GetString("write_NoROM", resourceCulture);
            }
        }
    }
}
